//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmsGatewayTurkcell.SmsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sdp.turkcell.com.tr/wsdl/generated", ConfigurationName="SmsService.NIFSendMessagePortType")]
    public interface NIFSendMessagePortType {
        
        // CODEGEN: Generating message contract since the operation SendSMS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sdp.turkcell.com.tr/services/action/SendMessage/SendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SmsGatewayTurkcell.SmsService.SendSMSResponse SendSMS(SmsGatewayTurkcell.SmsService.SendSMSRequest request);
        
        // CODEGEN: Generating message contract since the operation SendBinarySMS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sdp.turkcell.com.tr/services/action/SendMessage/SendBinarySMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SmsGatewayTurkcell.SmsService.SendBinarySMSResponse SendBinarySMS(SmsGatewayTurkcell.SmsService.SendBinarySMSRequest request);
        
        // CODEGEN: Generating message contract since the operation SendMMS is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sdp.turkcell.com.tr/services/action/SendMessage/SendMMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SmsGatewayTurkcell.SmsService.SendMMSResponse SendMMS(SmsGatewayTurkcell.SmsService.SendMMSRequest request);
        
        // CODEGEN: Generating message contract since the operation SendWAPPush is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://sdp.turkcell.com.tr/services/action/SendMessage/SendWAPPush", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SmsGatewayTurkcell.SmsService.SendWAPPushResponse SendWAPPush(SmsGatewayTurkcell.SmsService.SendWAPPushRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
    public partial class token : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sessionIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string sessionId {
            get {
                return this.sessionIdField;
            }
            set {
                this.sessionIdField = value;
                this.RaisePropertyChanged("sessionId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://sdp.turkcell.com/mapping/TSO")]
    public partial class CITEM_TYPE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cITEM_TEXTField;
        
        private string xSERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CITEM_TEXT {
            get {
                return this.cITEM_TEXTField;
            }
            set {
                this.cITEM_TEXTField = value;
                this.RaisePropertyChanged("CITEM_TEXT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string XSER {
            get {
                return this.xSERField;
            }
            set {
                this.xSERField = value;
                this.RaisePropertyChanged("XSER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
    public partial class SendSMSInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eXPIRY_DATEField;
        
        private SendSMSInputMESSAGE_CLASS mESSAGE_CLASSField;
        
        private bool mESSAGE_CLASSFieldSpecified;
        
        private string s_DATEField;
        
        private string sENDERField;
        
        private string sHORT_NUMBERField;
        
        private string sRC_MSISDNField;
        
        private string nREQField;
        
        private string[] tO_RECEIVERSField;
        
        private string[] mESSAGE_BODYField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EXPIRY_DATE {
            get {
                return this.eXPIRY_DATEField;
            }
            set {
                this.eXPIRY_DATEField = value;
                this.RaisePropertyChanged("EXPIRY_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SendSMSInputMESSAGE_CLASS MESSAGE_CLASS {
            get {
                return this.mESSAGE_CLASSField;
            }
            set {
                this.mESSAGE_CLASSField = value;
                this.RaisePropertyChanged("MESSAGE_CLASS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MESSAGE_CLASSSpecified {
            get {
                return this.mESSAGE_CLASSFieldSpecified;
            }
            set {
                this.mESSAGE_CLASSFieldSpecified = value;
                this.RaisePropertyChanged("MESSAGE_CLASSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string S_DATE {
            get {
                return this.s_DATEField;
            }
            set {
                this.s_DATEField = value;
                this.RaisePropertyChanged("S_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SENDER {
            get {
                return this.sENDERField;
            }
            set {
                this.sENDERField = value;
                this.RaisePropertyChanged("SENDER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SHORT_NUMBER {
            get {
                return this.sHORT_NUMBERField;
            }
            set {
                this.sHORT_NUMBERField = value;
                this.RaisePropertyChanged("SHORT_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SRC_MSISDN {
            get {
                return this.sRC_MSISDNField;
            }
            set {
                this.sRC_MSISDNField = value;
                this.RaisePropertyChanged("SRC_MSISDN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NREQ {
            get {
                return this.nREQField;
            }
            set {
                this.nREQField = value;
                this.RaisePropertyChanged("NREQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("msisdn", IsNullable=false)]
        public string[] TO_RECEIVERS {
            get {
                return this.tO_RECEIVERSField;
            }
            set {
                this.tO_RECEIVERSField = value;
                this.RaisePropertyChanged("TO_RECEIVERS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("message", IsNullable=false)]
        public string[] MESSAGE_BODY {
            get {
                return this.mESSAGE_BODYField;
            }
            set {
                this.mESSAGE_BODYField = value;
                this.RaisePropertyChanged("MESSAGE_BODY");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
    public enum SendSMSInputMESSAGE_CLASS {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
    public partial class SendSMSOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] statusCodeField;
        
        private string[] errorCodeField;
        
        private string[] errorDescriptionField;
        
        private TSOresult tSOresultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
        public string[] statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
        public string[] errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
        public string[] errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://sdp.turkcell.com/mapping/TSO", Order=3)]
        public TSOresult TSOresult {
            get {
                return this.tSOresultField;
            }
            set {
                this.tSOresultField = value;
                this.RaisePropertyChanged("TSOresult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdp.turkcell.com/mapping/TSO")]
    public partial class TSOresult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusCodeField;
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
        public SmsGatewayTurkcell.SmsService.token token;
        
        [System.ServiceModel.MessageHeaderAttribute(Name="transaction-list", Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
        [System.Xml.Serialization.XmlArrayAttribute("transaction-list")]
        [System.Xml.Serialization.XmlArrayItemAttribute("transaction-id", IsNullable=false)]
        public string[] transactionlist;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdp.turkcell.com.tr/mapping/generated", Order=0)]
        public SmsGatewayTurkcell.SmsService.SendSMSInput SendSMSInput;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(SmsGatewayTurkcell.SmsService.token token, string[] transactionlist, SmsGatewayTurkcell.SmsService.SendSMSInput SendSMSInput) {
            this.token = token;
            this.transactionlist = transactionlist;
            this.SendSMSInput = SendSMSInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdp.turkcell.com.tr/mapping/generated", Order=0)]
        public SmsGatewayTurkcell.SmsService.SendSMSOutput SendSMSOutput;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(SmsGatewayTurkcell.SmsService.SendSMSOutput SendSMSOutput) {
            this.SendSMSOutput = SendSMSOutput;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
    public partial class SendBinarySMSInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eXPIRY_DATEField;
        
        private SendBinarySMSInputMESSAGE_CLASS mESSAGE_CLASSField;
        
        private bool mESSAGE_CLASSFieldSpecified;
        
        private string s_DATEField;
        
        private string sENDERField;
        
        private string sHORT_NUMBERField;
        
        private string sRC_MSISDNField;
        
        private string nREQField;
        
        private string[] tO_RECEIVERSField;
        
        private CITEM_TYPE[][] dELIVERY_CONTENTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EXPIRY_DATE {
            get {
                return this.eXPIRY_DATEField;
            }
            set {
                this.eXPIRY_DATEField = value;
                this.RaisePropertyChanged("EXPIRY_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SendBinarySMSInputMESSAGE_CLASS MESSAGE_CLASS {
            get {
                return this.mESSAGE_CLASSField;
            }
            set {
                this.mESSAGE_CLASSField = value;
                this.RaisePropertyChanged("MESSAGE_CLASS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MESSAGE_CLASSSpecified {
            get {
                return this.mESSAGE_CLASSFieldSpecified;
            }
            set {
                this.mESSAGE_CLASSFieldSpecified = value;
                this.RaisePropertyChanged("MESSAGE_CLASSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string S_DATE {
            get {
                return this.s_DATEField;
            }
            set {
                this.s_DATEField = value;
                this.RaisePropertyChanged("S_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SENDER {
            get {
                return this.sENDERField;
            }
            set {
                this.sENDERField = value;
                this.RaisePropertyChanged("SENDER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SHORT_NUMBER {
            get {
                return this.sHORT_NUMBERField;
            }
            set {
                this.sHORT_NUMBERField = value;
                this.RaisePropertyChanged("SHORT_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SRC_MSISDN {
            get {
                return this.sRC_MSISDNField;
            }
            set {
                this.sRC_MSISDNField = value;
                this.RaisePropertyChanged("SRC_MSISDN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string NREQ {
            get {
                return this.nREQField;
            }
            set {
                this.nREQField = value;
                this.RaisePropertyChanged("NREQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("msisdn", IsNullable=false)]
        public string[] TO_RECEIVERS {
            get {
                return this.tO_RECEIVERSField;
            }
            set {
                this.tO_RECEIVERSField = value;
                this.RaisePropertyChanged("TO_RECEIVERS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Namespace="http://sdp.turkcell.com/mapping/TSO", Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CITEM_LIST", IsNullable=false)]
        [System.Xml.Serialization.XmlArrayItemAttribute("CITEM", IsNullable=false, NestingLevel=1)]
        public CITEM_TYPE[][] DELIVERY_CONTENT {
            get {
                return this.dELIVERY_CONTENTField;
            }
            set {
                this.dELIVERY_CONTENTField = value;
                this.RaisePropertyChanged("DELIVERY_CONTENT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
    public enum SendBinarySMSInputMESSAGE_CLASS {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
    public partial class SendBinarySMSOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] statusCodeField;
        
        private string[] errorCodeField;
        
        private string[] errorDescriptionField;
        
        private TSOresult tSOresultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
        public string[] statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
        public string[] errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
        public string[] errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://sdp.turkcell.com/mapping/TSO", Order=3)]
        public TSOresult TSOresult {
            get {
                return this.tSOresultField;
            }
            set {
                this.tSOresultField = value;
                this.RaisePropertyChanged("TSOresult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBinarySMSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
        public SmsGatewayTurkcell.SmsService.token token;
        
        [System.ServiceModel.MessageHeaderAttribute(Name="transaction-list", Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
        [System.Xml.Serialization.XmlArrayAttribute("transaction-list")]
        [System.Xml.Serialization.XmlArrayItemAttribute("transaction-id", IsNullable=false)]
        public string[] transactionlist;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdp.turkcell.com.tr/mapping/generated", Order=0)]
        public SmsGatewayTurkcell.SmsService.SendBinarySMSInput SendBinarySMSInput;
        
        public SendBinarySMSRequest() {
        }
        
        public SendBinarySMSRequest(SmsGatewayTurkcell.SmsService.token token, string[] transactionlist, SmsGatewayTurkcell.SmsService.SendBinarySMSInput SendBinarySMSInput) {
            this.token = token;
            this.transactionlist = transactionlist;
            this.SendBinarySMSInput = SendBinarySMSInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendBinarySMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdp.turkcell.com.tr/mapping/generated", Order=0)]
        public SmsGatewayTurkcell.SmsService.SendBinarySMSOutput SendBinarySMSOutput;
        
        public SendBinarySMSResponse() {
        }
        
        public SendBinarySMSResponse(SmsGatewayTurkcell.SmsService.SendBinarySMSOutput SendBinarySMSOutput) {
            this.SendBinarySMSOutput = SendBinarySMSOutput;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
    public partial class SendMMSInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string sUBJECTField;
        
        private string eXPIRY_DATEField;
        
        private SendMMSInputMESSAGE_CLASS mESSAGE_CLASSField;
        
        private bool mESSAGE_CLASSFieldSpecified;
        
        private string s_DATEField;
        
        private string tIMESTAMPField;
        
        private string sHORT_NUMBERField;
        
        private string sRC_MSISDNField;
        
        private string nREQField;
        
        private string[] tO_RECEIVERSField;
        
        private string[] mESSAGE_BODYField;
        
        private string mIME_DATAField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SUBJECT {
            get {
                return this.sUBJECTField;
            }
            set {
                this.sUBJECTField = value;
                this.RaisePropertyChanged("SUBJECT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EXPIRY_DATE {
            get {
                return this.eXPIRY_DATEField;
            }
            set {
                this.eXPIRY_DATEField = value;
                this.RaisePropertyChanged("EXPIRY_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public SendMMSInputMESSAGE_CLASS MESSAGE_CLASS {
            get {
                return this.mESSAGE_CLASSField;
            }
            set {
                this.mESSAGE_CLASSField = value;
                this.RaisePropertyChanged("MESSAGE_CLASS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool MESSAGE_CLASSSpecified {
            get {
                return this.mESSAGE_CLASSFieldSpecified;
            }
            set {
                this.mESSAGE_CLASSFieldSpecified = value;
                this.RaisePropertyChanged("MESSAGE_CLASSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string S_DATE {
            get {
                return this.s_DATEField;
            }
            set {
                this.s_DATEField = value;
                this.RaisePropertyChanged("S_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TIMESTAMP {
            get {
                return this.tIMESTAMPField;
            }
            set {
                this.tIMESTAMPField = value;
                this.RaisePropertyChanged("TIMESTAMP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string SHORT_NUMBER {
            get {
                return this.sHORT_NUMBERField;
            }
            set {
                this.sHORT_NUMBERField = value;
                this.RaisePropertyChanged("SHORT_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SRC_MSISDN {
            get {
                return this.sRC_MSISDNField;
            }
            set {
                this.sRC_MSISDNField = value;
                this.RaisePropertyChanged("SRC_MSISDN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string NREQ {
            get {
                return this.nREQField;
            }
            set {
                this.nREQField = value;
                this.RaisePropertyChanged("NREQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("msisdn", IsNullable=false)]
        public string[] TO_RECEIVERS {
            get {
                return this.tO_RECEIVERSField;
            }
            set {
                this.tO_RECEIVERSField = value;
                this.RaisePropertyChanged("TO_RECEIVERS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=9)]
        [System.Xml.Serialization.XmlArrayItemAttribute("message", IsNullable=false)]
        public string[] MESSAGE_BODY {
            get {
                return this.mESSAGE_BODYField;
            }
            set {
                this.mESSAGE_BODYField = value;
                this.RaisePropertyChanged("MESSAGE_BODY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MIME_DATA {
            get {
                return this.mIME_DATAField;
            }
            set {
                this.mIME_DATAField = value;
                this.RaisePropertyChanged("MIME_DATA");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
    public enum SendMMSInputMESSAGE_CLASS {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
    public partial class SendMMSOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] statusCodeField;
        
        private string[] errorCodeField;
        
        private string[] errorDescriptionField;
        
        private TSOresult tSOresultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
        public string[] statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
        public string[] errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
        public string[] errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://sdp.turkcell.com/mapping/TSO", Order=3)]
        public TSOresult TSOresult {
            get {
                return this.tSOresultField;
            }
            set {
                this.tSOresultField = value;
                this.RaisePropertyChanged("TSOresult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMMSRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
        public SmsGatewayTurkcell.SmsService.token token;
        
        [System.ServiceModel.MessageHeaderAttribute(Name="transaction-list", Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
        [System.Xml.Serialization.XmlArrayAttribute("transaction-list")]
        [System.Xml.Serialization.XmlArrayItemAttribute("transaction-id", IsNullable=false)]
        public string[] transactionlist;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdp.turkcell.com.tr/mapping/generated", Order=0)]
        public SmsGatewayTurkcell.SmsService.SendMMSInput SendMMSInput;
        
        public SendMMSRequest() {
        }
        
        public SendMMSRequest(SmsGatewayTurkcell.SmsService.token token, string[] transactionlist, SmsGatewayTurkcell.SmsService.SendMMSInput SendMMSInput) {
            this.token = token;
            this.transactionlist = transactionlist;
            this.SendMMSInput = SendMMSInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdp.turkcell.com.tr/mapping/generated", Order=0)]
        public SmsGatewayTurkcell.SmsService.SendMMSOutput SendMMSOutput;
        
        public SendMMSResponse() {
        }
        
        public SendMMSResponse(SmsGatewayTurkcell.SmsService.SendMMSOutput SendMMSOutput) {
            this.SendMMSOutput = SendMMSOutput;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
    public partial class SendWAPPushInput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string eXPIRY_DATEField;
        
        private string s_DATEField;
        
        private string sENDERField;
        
        private string sHORT_NUMBERField;
        
        private string sRC_MSISDNField;
        
        private string nREQField;
        
        private string[] tO_RECEIVERSField;
        
        private string[] mESSAGE_BODYField;
        
        private string[] mESSAGE_HREFField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EXPIRY_DATE {
            get {
                return this.eXPIRY_DATEField;
            }
            set {
                this.eXPIRY_DATEField = value;
                this.RaisePropertyChanged("EXPIRY_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string S_DATE {
            get {
                return this.s_DATEField;
            }
            set {
                this.s_DATEField = value;
                this.RaisePropertyChanged("S_DATE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SENDER {
            get {
                return this.sENDERField;
            }
            set {
                this.sENDERField = value;
                this.RaisePropertyChanged("SENDER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SHORT_NUMBER {
            get {
                return this.sHORT_NUMBERField;
            }
            set {
                this.sHORT_NUMBERField = value;
                this.RaisePropertyChanged("SHORT_NUMBER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SRC_MSISDN {
            get {
                return this.sRC_MSISDNField;
            }
            set {
                this.sRC_MSISDNField = value;
                this.RaisePropertyChanged("SRC_MSISDN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string NREQ {
            get {
                return this.nREQField;
            }
            set {
                this.nREQField = value;
                this.RaisePropertyChanged("NREQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("msisdn", IsNullable=false)]
        public string[] TO_RECEIVERS {
            get {
                return this.tO_RECEIVERSField;
            }
            set {
                this.tO_RECEIVERSField = value;
                this.RaisePropertyChanged("TO_RECEIVERS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=7)]
        [System.Xml.Serialization.XmlArrayItemAttribute("message", IsNullable=false)]
        public string[] MESSAGE_BODY {
            get {
                return this.mESSAGE_BODYField;
            }
            set {
                this.mESSAGE_BODYField = value;
                this.RaisePropertyChanged("MESSAGE_BODY");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("HREF", IsNullable=false)]
        public string[] MESSAGE_HREF {
            get {
                return this.mESSAGE_HREFField;
            }
            set {
                this.mESSAGE_HREFField = value;
                this.RaisePropertyChanged("MESSAGE_HREF");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
    public partial class SendWAPPushOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] statusCodeField;
        
        private string[] errorCodeField;
        
        private string[] errorDescriptionField;
        
        private TSOresult tSOresultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
        public string[] statusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("statusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
        public string[] errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("value", IsNullable=false)]
        public string[] errorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
                this.RaisePropertyChanged("errorDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://sdp.turkcell.com/mapping/TSO", Order=3)]
        public TSOresult TSOresult {
            get {
                return this.tSOresultField;
            }
            set {
                this.tSOresultField = value;
                this.RaisePropertyChanged("TSOresult");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWAPPushRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
        public SmsGatewayTurkcell.SmsService.token token;
        
        [System.ServiceModel.MessageHeaderAttribute(Name="transaction-list", Namespace="http://sdp.turkcell.com.tr/mapping/generated")]
        [System.Xml.Serialization.XmlArrayAttribute("transaction-list")]
        [System.Xml.Serialization.XmlArrayItemAttribute("transaction-id", IsNullable=false)]
        public string[] transactionlist;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdp.turkcell.com.tr/mapping/generated", Order=0)]
        public SmsGatewayTurkcell.SmsService.SendWAPPushInput SendWAPPushInput;
        
        public SendWAPPushRequest() {
        }
        
        public SendWAPPushRequest(SmsGatewayTurkcell.SmsService.token token, string[] transactionlist, SmsGatewayTurkcell.SmsService.SendWAPPushInput SendWAPPushInput) {
            this.token = token;
            this.transactionlist = transactionlist;
            this.SendWAPPushInput = SendWAPPushInput;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendWAPPushResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://sdp.turkcell.com.tr/mapping/generated", Order=0)]
        public SmsGatewayTurkcell.SmsService.SendWAPPushOutput SendWAPPushOutput;
        
        public SendWAPPushResponse() {
        }
        
        public SendWAPPushResponse(SmsGatewayTurkcell.SmsService.SendWAPPushOutput SendWAPPushOutput) {
            this.SendWAPPushOutput = SendWAPPushOutput;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NIFSendMessagePortTypeChannel : SmsGatewayTurkcell.SmsService.NIFSendMessagePortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NIFSendMessagePortTypeClient : System.ServiceModel.ClientBase<SmsGatewayTurkcell.SmsService.NIFSendMessagePortType>, SmsGatewayTurkcell.SmsService.NIFSendMessagePortType {
        
        public NIFSendMessagePortTypeClient() {
        }
        
        public NIFSendMessagePortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NIFSendMessagePortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NIFSendMessagePortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NIFSendMessagePortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGatewayTurkcell.SmsService.SendSMSResponse SmsGatewayTurkcell.SmsService.NIFSendMessagePortType.SendSMS(SmsGatewayTurkcell.SmsService.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public SmsGatewayTurkcell.SmsService.SendSMSOutput SendSMS(SmsGatewayTurkcell.SmsService.token token, string[] transactionlist, SmsGatewayTurkcell.SmsService.SendSMSInput SendSMSInput) {
            SmsGatewayTurkcell.SmsService.SendSMSRequest inValue = new SmsGatewayTurkcell.SmsService.SendSMSRequest();
            inValue.token = token;
            inValue.transactionlist = transactionlist;
            inValue.SendSMSInput = SendSMSInput;
            SmsGatewayTurkcell.SmsService.SendSMSResponse retVal = ((SmsGatewayTurkcell.SmsService.NIFSendMessagePortType)(this)).SendSMS(inValue);
            return retVal.SendSMSOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGatewayTurkcell.SmsService.SendBinarySMSResponse SmsGatewayTurkcell.SmsService.NIFSendMessagePortType.SendBinarySMS(SmsGatewayTurkcell.SmsService.SendBinarySMSRequest request) {
            return base.Channel.SendBinarySMS(request);
        }
        
        public SmsGatewayTurkcell.SmsService.SendBinarySMSOutput SendBinarySMS(SmsGatewayTurkcell.SmsService.token token, string[] transactionlist, SmsGatewayTurkcell.SmsService.SendBinarySMSInput SendBinarySMSInput) {
            SmsGatewayTurkcell.SmsService.SendBinarySMSRequest inValue = new SmsGatewayTurkcell.SmsService.SendBinarySMSRequest();
            inValue.token = token;
            inValue.transactionlist = transactionlist;
            inValue.SendBinarySMSInput = SendBinarySMSInput;
            SmsGatewayTurkcell.SmsService.SendBinarySMSResponse retVal = ((SmsGatewayTurkcell.SmsService.NIFSendMessagePortType)(this)).SendBinarySMS(inValue);
            return retVal.SendBinarySMSOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGatewayTurkcell.SmsService.SendMMSResponse SmsGatewayTurkcell.SmsService.NIFSendMessagePortType.SendMMS(SmsGatewayTurkcell.SmsService.SendMMSRequest request) {
            return base.Channel.SendMMS(request);
        }
        
        public SmsGatewayTurkcell.SmsService.SendMMSOutput SendMMS(SmsGatewayTurkcell.SmsService.token token, string[] transactionlist, SmsGatewayTurkcell.SmsService.SendMMSInput SendMMSInput) {
            SmsGatewayTurkcell.SmsService.SendMMSRequest inValue = new SmsGatewayTurkcell.SmsService.SendMMSRequest();
            inValue.token = token;
            inValue.transactionlist = transactionlist;
            inValue.SendMMSInput = SendMMSInput;
            SmsGatewayTurkcell.SmsService.SendMMSResponse retVal = ((SmsGatewayTurkcell.SmsService.NIFSendMessagePortType)(this)).SendMMS(inValue);
            return retVal.SendMMSOutput;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmsGatewayTurkcell.SmsService.SendWAPPushResponse SmsGatewayTurkcell.SmsService.NIFSendMessagePortType.SendWAPPush(SmsGatewayTurkcell.SmsService.SendWAPPushRequest request) {
            return base.Channel.SendWAPPush(request);
        }
        
        public SmsGatewayTurkcell.SmsService.SendWAPPushOutput SendWAPPush(SmsGatewayTurkcell.SmsService.token token, string[] transactionlist, SmsGatewayTurkcell.SmsService.SendWAPPushInput SendWAPPushInput) {
            SmsGatewayTurkcell.SmsService.SendWAPPushRequest inValue = new SmsGatewayTurkcell.SmsService.SendWAPPushRequest();
            inValue.token = token;
            inValue.transactionlist = transactionlist;
            inValue.SendWAPPushInput = SendWAPPushInput;
            SmsGatewayTurkcell.SmsService.SendWAPPushResponse retVal = ((SmsGatewayTurkcell.SmsService.NIFSendMessagePortType)(this)).SendWAPPush(inValue);
            return retVal.SendWAPPushOutput;
        }
    }
}
